/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdint.h>

#define GPIOA_BASE_ADDR             0x40020000UL

#define RCC_BASE_ADDR              0x40023800UL
#define RCC_CFGR_OFFSET        	   0x08UL
#define RCC_CFGR_ADDR          (RCC_BASE_ADDR+RCC_CFGR_OFFSET)

int main(void)
{
	uint32_t *pRCC_CFGR =   (uint32_t*) RCC_CFGR_ADDR;
	// Configure MCO1 to use HSI clock
	*pRCC_CFGR &= ~(0x3<<21);
	// Setting  MCO1 prescaler to divide by 2
	*pRCC_CFGR |= (1<<26);

	// Configure RCC AHB1 register and set bit 1 for GPIOA
	uint32_t *pRCC_AHB1ENR =   (uint32_t*) (RCC_BASE_ADDR+0x30);
	*pRCC_AHB1ENR |= (1<<0);

	// Configure GPIOA 8pin as alternate function mode
	uint32_t *pGPIOA_MODER =   (uint32_t*) (GPIOA_BASE_ADDR+0x00);
	*pGPIOA_MODER &= ~(0x3<<16);
	*pGPIOA_MODER |= (0x2<<16);

	// Set mode 0 for GPIOA P8
	uint32_t *pGPIOA_AFRH =   (uint32_t*) (GPIOA_BASE_ADDR+0x24);
	*pGPIOA_AFRH &= ~(0xF<<0);

	for(;;);
}
